
```{r load_packages, include = FALSE}

library(readr)
library(tidyr)
library(ggplot2)
library(cowplot)
library(knitr)
library(boot)
library(dplyr)
library(ggthemes)
library(langcog)
library(broom)
library(plyr)
```


The main summary results 

```{r }

#uplaod data
gold_eng <- read_delim("res/results_gold_Eng.txt", delim = "\t") 
gold_jap <- read_delim("res/results_gold_Jap.txt", delim = "\t") 
seg_eng <- read_delim("res/results_seg_Eng.txt", delim = "\t") 
seg_jap <- read_delim("res/results_seg_Jap.txt", delim = "\t") 
rand_eng <- read_delim("res/results_rand_Eng.txt", delim = "\t")
rand_jap <- read_delim("res/results_rand_Jap.txt", delim = "\t")


data_eng <- gold_eng %>%
  bind_rows(seg_eng) %>%
  bind_rows(rand_eng)
  
data_eng$variation <- mapvalues(data_eng$variation, 
                                     from = c('h_2', 'h_4', 'h_10', 'h_19', 'phonemic', 'htk_80', 'htk_160', 'htk_320'),
                                
                                     to = c(2, 4,  10,  19, 41,  80,  160, 320))

data_jap <- gold_jap %>%
  bind_rows(seg_jap) %>%
  bind_rows(rand_jap)

data_jap$variation <- mapvalues(data_jap$variation, 
                                     from = c('h_2', 'h_4', 'h_8', 'h_13', 'phonemic', 'htk_50', 'htk_100', 'htk_200'),
                                
                                     to = c(2, 4,  8,  13, 25,  50,  100, 200))


data_all <- data_eng %>%
  bind_rows(data_jap)

data_all$variation <- as.numeric(data_all$variation)

data_all$language <- mapvalues(data_all$language, 
                                     from = c('Eng', 'Jap'),
                                     to = c('English', 'Japanese'))

data_all$Segmentation <- mapvalues(data_all$Segmentation, 
                                     from = c('gold', 'seg', 'rand'),
                                     to = c('Ideal', 'Unsupervised', 'Random'))

data_all$Segmentation <- factor(data_all$Segmentation, 
                                    levels = c('Ideal', 'Unsupervised', 'Random'))

data_sum <- data_all %>%
  dplyr::group_by(language, Segmentation, variation) %>%
  dplyr::summarise(mean = mean(AUC),
            sd = sd(AUC)) %>%
  dplyr::mutate(sd_up = mean + 2*sd,
         sd_low = mean - 2*sd) %>%
  dplyr::rename(AUC= mean)


ggplot(data_all, 
      aes(x = variation, y = AUC)) +
  geom_point(col='black', fill = "white", alpha = 0.05)+
  geom_point(data = subset(data_all, variation==25 | variation == 41), col='red', alpha = 0.05)+

  geom_line(data = data_sum, col='black')+
geom_point(data = data_sum, col='black', size = 2)+
  #stat_summary(fun.y="mean", geom="point", col='red', size=0.5)+
  scale_x_log10() +
theme(aspect.ratio = 0.7, legend.title = element_text(size=8)) +  
  theme_few()+
  facet_grid(Segmentation ~ language) +
  theme(aspect.ratio = 0.7)+
  xlab("Inventory size") +ylab("Differentiation score (AUC)")


  
```



Histogram of optimality across parameter settings

```{r}

#Do the histogram through calculation
histo <- data_all %>%
  group_by(language, Segmentation, context, dimension) %>%
  filter(AUC == max(AUC)) %>%
  arrange(language, Segmentation, context, dimension, variation)

ggplot(histo, 
      aes(x = variation)) +
  geom_histogram(aes(y = (..count..)/tapply(..count..,..PANEL..,sum)[..PANEL..]),
                 binwidth=0.3)+
  scale_x_log10() +
  theme_few() + 
  theme(aspect.ratio = 0.7, legend.title = element_text(size=8)) +  facet_grid(Segmentation ~ language)+
  scale_y_continuous(labels = scales::percent)+
  xlab("Inventory size") +ylab("Percent optimal")


```


The distribution for the parameter setting dim=20, context=20

```{r}
dist_Eng <- read_delim("res/dist_gold_Eng.txt", delim = " ") %>%
  mutate(language = 'English') %>%
  dplyr::rename(distribution=dist)

dist_Jap <- read_delim("res/dist_gold_Jap.txt", delim = " ") %>%
  mutate(language = 'Japanese') %>%
  dplyr::rename(distribution=dist)


dist_Eng$level <- mapvalues(dist_Eng$level, 
                                     from = c('h_2', 'h_4', 'h_10', 'h_19', 'phonemic', 'htk_80', 'htk_160', 'htk_320'),
                                     to = c('phonemic-4', 'phonemic-3', 'phonemic-2', 'phonemic-1', 'phonemic', 'phonemic+1', 'phonemic+2', 'phonemic+3'))

dist_Jap$level <- mapvalues(dist_Jap$level, 
                                     from = c('h_2', 'h_4', 'h_8', 'h_13', 'phonemic', 'htk_50', 'htk_100', 'htk_200'),
                                     to = c('phonemic-4', 'phonemic-3', 'phonemic-2', 'phonemic-1', 'phonemic', 'phonemic+1', 'phonemic+2', 'phonemic+3'))

dist <- bind_rows(dist_Eng, dist_Jap)

dist$distribution <- as.character(dist$distribution)

dist$distribution <- mapvalues(dist$distribution, from=c('0', '1'), to =c('between', 'within'))

dist$level <- factor(dist$level, levels =c('phonemic-4', 'phonemic-3', 'phonemic-2', 'phonemic-1', 'phonemic', 'phonemic+1', 'phonemic+2', 'phonemic+3'))

#ggplot(self2)+geom_density(aes(x=value, y=..scaled.., fill=dist),  alpha=1/3) +facet_grid(. ~ level)

ggplot(dist,  aes(value, fill=distribution))+
  geom_density(aes(y=..scaled..), alpha=0.2, adjust = 3) +
  scale_y_continuous(breaks =c(0,0.5,1))+
  theme_few()+
  facet_grid(language ~ level)+
  theme(aspect.ratio = 0.7, 
        axis.text=element_text(size=7, angle = 45),
        strip.text.x = element_text(size=7),
        strip.text.y = element_text(size=6)
        ) +
  xlab("Cosine similarity") +ylab("Count")

```

Score for different sizes

```{r}
#uplaod data
gold_eng_50k <- gold_eng %>%
  mutate(size='50k')
gold_jap_50k <- gold_jap %>%
  mutate(size='50k')
gold_eng_5k <- read_delim("res/results_gold_Eng_5k.txt", delim = "\t") %>%
  mutate(size='5k')
gold_jap_5k <- read_delim("res/results_gold_Jap_5k.txt", delim = "\t") %>%
  mutate(size='5k')
gold_eng_500 <- read_delim("res/results_gold_Eng_500.txt", delim = "\t") %>%
  mutate(size='500')
gold_jap_500 <- read_delim("res/results_gold_Jap_500.txt", delim = "\t") %>%
  mutate(size='500')
gold_eng_50 <- read_delim("res/results_gold_Eng_50.txt", delim = "\t") %>%
  mutate(size='50') 
gold_jap_50 <- read_delim("res/results_gold_Jap_50.txt", delim = "\t") %>%
  mutate(size='50')


size_eng <- gold_eng_50k %>%
  bind_rows(gold_eng_5k) %>%
  bind_rows(gold_eng_500) %>%
  bind_rows(gold_eng_50)

size_eng$variation <- mapvalues(size_eng$variation, 
                                     from = c('h_2', 'h_4', 'h_10', 'h_19', 'phonemic', 'htk_80', 'htk_160', 'htk_320'),
                                
                                     to = c(2, 4,  10,  19, 41,  80,  160, 320))


size_jap <- gold_jap_50k %>%
  bind_rows(gold_jap_5k) %>%
  bind_rows(gold_jap_500) %>%
  bind_rows(gold_jap_50)

size_jap$variation <- mapvalues(size_jap$variation, 
                                     from = c('h_2', 'h_4', 'h_8', 'h_13', 'phonemic', 'htk_50', 'htk_100', 'htk_200'),
                                
                                     to = c(2, 4,  8,  13, 25,  50,  100, 200))



size_all <- size_eng %>%
  bind_rows(size_jap)

size_all$language <- mapvalues(size_all$language, 
                                     from = c('Eng', 'Jap'),
                                     to = c('English', 'Japanese'))

size_all$size <- factor(size_all$size, levels = c('50k', '5k', '500', '50'))

size_all$variation <- as.numeric(size_all$variation)

ggplot(size_all, 
      aes(x = variation, y = AUC)) +
  geom_point(col='black', fill = "white", alpha = 0.05)+
  geom_point(data = subset(size_all, variation==25 | variation == 41), col='red', alpha = 0.05)+
  #stat_summary(fun.y="mean", geom="point", col='blue', size=0.5)+
  scale_x_log10() +
theme(aspect.ratio = 0.7, legend.title = element_text(size=8)) +  
  theme_few()+
  facet_grid(size ~ language) +
  theme(aspect.ratio = 0.7)+
  xlab("Inventory size") +ylab("Differentiation score (AUC)")


```


Histogram for size

```{r}

#Do the histogram through calculation
histo_size <- size_all %>%
  group_by(language, size, context, dimension) %>%
  filter(AUC == max(AUC)) %>%
  arrange(language, size, context, dimension, variation)

ggplot(histo_size, 
      aes(x = variation)) +
  geom_histogram(aes(y = (..count..)/tapply(..count..,..PANEL..,sum)[..PANEL..]),
                 binwidth=0.3)+
  scale_x_log10(limits = c(1.9,321)) +
  theme_few() + 
  theme(aspect.ratio = 0.7, legend.title = element_text(size=8)) +  
  facet_grid(size ~ language)+
  scale_y_continuous(labels = scales::percent)+
  xlab("Inventory size") +ylab("Percent optimal")


```
